[tool.pyright]
extraPaths = [
    "./modules/detectron2",
    "./modules/b3d",
    "./modules/boxmot",
    "./modules/transformers/src",
    "./modules/TrackEval",
    "./modules/darknet"
]
typeCheckingMode = "basic"
