EXEC:
  DATASETS:
    - caldot1-yolo12
    - caldot2-yolo12
    - jnc0
    - jnc2
    - jnc6
    - jnc7
    - caldot1
    - caldot2
    # - caldot1-fasterrcnn
    # - caldot2-fasterrcnn
    # - ams
  VIDEO_SETS:
    - train
    - valid
    - test
  CLASSIFIERS:
    - YoloN
    - ShuffleNet05
    - MobileNetS
    - Perfect
  TILE_SIZES:
    - 60
  TILEPADDING_MODES:
    - none
    - connected
    - disconnected

DATA:
  SOURCE_DIR: /polyis-data/sources
  DATASETS_DIR: /polyis-data/datasets
  CACHE_DIR: /polyis-cache/

OPS:
  preprocess_dataset:
    batch_size: 128
    segment_size: 60
    num_segments: 18